## Aktionsabfragen

Lies im Buch Seite 59 durch. Mit ihrer Hilfe sollten Sie die nachfolgende Aufgaben lösen können. 

Es gibt vier Typen von Aktionsabfragen. Die Tabellenerstellungsabfragen sind im Buch etwas knapp dargestellt. Deshalb soll hier eine Beispielaufgabe dazu mit Lösung besprochen werden.

Hilfreich sind auch folgende Tutorial-Seiten:

|Aktionsabfrage|Link|
|:--- |:--- |
|Tabellenerstellung|http://www.sqlitetutorial.net/sqlite-create-table/| 
|Anfügeabfrage|http://www.sqlitetutorial.net/sqlite-insert/|
|Aktualisierungsabfrage|http://www.sqlitetutorial.net/sqlite-update/|
|Löschabfrage|http://www.sqlitetutorial.net/sqlite-delete/|

### Beispielaufgabe Tabellenerstellungsabfrage:

Erstellen Sie eine Datenbankdatei mit Namen <i>freunde.db</i> und legen Sie dort eine Tabelle "Freunde" an, die folgende Attribute enthält: Name, Telefonnummer, Wohnort. Wählen Sie für die Attribute geeignete Datentypen aus. Der Primärschlüssel soll der Name sein.

#### Hinweis:

Bei Aktionsabfragen muss in einem zusätzlichen Schritt das Verändern der Daten explizit freigegeben werden. Das geschieht mit der `.commit()`-Methode der Datenbankverbindung.

#### Lösung:

In [20]:
import sqlite3 

datenbankverbindung = sqlite3.connect( "freunde.db") 

cursor = datenbankverbindung.cursor() 

cursor.execute("CREATE TABLE Freunde ( Name TEXT PRIMARY KEY, Telefonnummer INTEGER, Wohnort TEXT );") 

datenbankverbindung.commit()

ergebnis = cursor.fetchall() 
print ( ergebnis )

datenbankverbindung.close() 

OperationalError: table Freunde already exists

### Hinweis:

Wenn man obigen Code ein zweites Mal ausführt, gibt das die Fehlermeldung `OperationalError: table Freunde already exists` obwohl der SQL-Befehl richtig ist. Das liegt daran, dass die Tabelle "Freunde" schon vorhanden ist und nun überschrieben würde. Soll die Tabelle nur erstellt werden, wenn sie noch nicht vorhanden ist, kann man das SQL-Statement um `IF NOT EXISTS` erweitern:

In [2]:
import sqlite3 

datenbankverbindung = sqlite3.connect( "freunde.db") 

cursor = datenbankverbindung.cursor() 

cursor.execute("CREATE TABLE IF NOT EXISTS Freunde ( Name TEXT PRIMARY KEY, Telefonnummer INTEGER, Wohnort TEXT );") 

datenbankverbindung.commit()

ergebnis = cursor.fetchall() 
print ( ergebnis )

datenbankverbindung.close() 

[]


## Aufgabe 22:

Speichere das Ergebnis unter *VornameNachname*-aufgabe22.ipynb auf Laufwerk H:.

1. Füge in die Tabelle "Freunde" die Freunde "Donald", "Daisy" und "Dagobert" mit den Telefonnummern 117, 118 und 119 ein. Alle drei wohnen in Entenhausen. Überprüfe durch ein anschließendes `SELECT`-Statement, ob die Werte auch richtig eingetragen wurden

[('Donald', 117, 'Entenhausen'), ('Daisy', 118, 'Entenhausen'), ('Dagobert', 119, 'Entenhausen')]


2. Lösche "Dagobert" aus der "Freunde"-Tabelle. Überprüfe das Ergebnis durch `SELECT`.

[('Donald', 117, 'Entenhausen'), ('Daisy', 118, 'Entenhausen')]


3. Ändern Sie den Namen von "Donald" in "Phantomias" und seine Rufnummer in 999. Überprüfen Sie das Ergebnis.

[('Phantomias', 999, 'Entenhausen'), ('Daisy', 118, 'Entenhausen')]


### Hinweis:

Sollten Sie die Tabelle in einen Zustand gebracht haben, in der sie sie zurücksetzen möchten, so können Sie sie mit dem Statement `DROP TABLE <tabelle>` komplett löschen.

In [33]:
import sqlite3 

datenbankverbindung = sqlite3.connect( "freunde.db") 

cursor = datenbankverbindung.cursor() 

cursor.execute("DROP TABLE Freunde;") 

datenbankverbindung.commit()

ergebnis = cursor.fetchall() 
print ( ergebnis )

datenbankverbindung.close() 

[]


### Lösung:

1. `[('Donald', 117, 'Entenhausen'), ('Daisy', 118, 'Entenhausen'), ('Dagobert', 119, 'Entenhausen')]`

2. `[('Donald', 117, 'Entenhausen'), ('Daisy', 118, 'Entenhausen')]`

3. `[('Phantomias', 999, 'Entenhausen'), ('Daisy', 118, 'Entenhausen')]`